// <auto-generated />
using System;
using CryptoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250728220728_AddEngineeredFeaturesToTransaction1")]
    partial class AddEngineeredFeaturesToTransaction1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CryptoApi.Models.CoinData", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("FearandGreed")
                        .HasColumnType("float");

                    b.Property<double?>("PercentChange1h")
                        .HasColumnType("float");

                    b.Property<double?>("PercentChange24h")
                        .HasColumnType("float");

                    b.Property<double?>("PercentChange30d")
                        .HasColumnType("float");

                    b.Property<double?>("PercentChange60d")
                        .HasColumnType("float");

                    b.Property<double?>("PercentChange7d")
                        .HasColumnType("float");

                    b.Property<double?>("PercentChange90d")
                        .HasColumnType("float");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Volume24h")
                        .HasColumnType("float");

                    b.Property<double?>("VolumeChange24h")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("CoinDatas");
                });

            modelBuilder.Entity("CryptoApi.Models.FeatureEngineering", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("BollingerBandBreakout")
                        .HasColumnType("bit");

                    b.Property<bool?>("BollingerBandSqueeze")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("FearandGreed_Lag_1")
                        .HasColumnType("float");

                    b.Property<double?>("FearandGreed_Lag_2")
                        .HasColumnType("float");

                    b.Property<bool?>("MeanReversionLongSignal")
                        .HasColumnType("bit");

                    b.Property<bool?>("MeanReversionShortSignal")
                        .HasColumnType("bit");

                    b.Property<bool?>("MomentumConfirmed")
                        .HasColumnType("bit");

                    b.Property<double?>("MomentumScore")
                        .HasColumnType("float");

                    b.Property<bool?>("MultiFactorConfluenceSignal")
                        .HasColumnType("bit");

                    b.Property<double?>("Predicted_Price_1h_Stable")
                        .HasColumnType("float");

                    b.Property<double?>("Price_Deviation_Pct")
                        .HasColumnType("float");

                    b.Property<double?>("Price_Lag_1")
                        .HasColumnType("float");

                    b.Property<double?>("Price_Lag_2")
                        .HasColumnType("float");

                    b.Property<double?>("Price_Momentum_1h")
                        .HasColumnType("float");

                    b.Property<double?>("Price_Rolling_Mean_3h")
                        .HasColumnType("float");

                    b.Property<double?>("SentimentScore")
                        .HasColumnType("float");

                    b.Property<double?>("SentimentScore_Lag_1")
                        .HasColumnType("float");

                    b.Property<double?>("SentimentScore_Lag_2")
                        .HasColumnType("float");

                    b.Property<double?>("Sentiment_Momentum_1h")
                        .HasColumnType("float");

                    b.Property<double?>("Sentiment_Rolling_Mean_3h")
                        .HasColumnType("float");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Volume24h_Lag_1")
                        .HasColumnType("float");

                    b.Property<double?>("Volume24h_Lag_2")
                        .HasColumnType("float");

                    b.Property<double?>("Volume24h_Rolling_Mean_24h")
                        .HasColumnType("float");

                    b.Property<double?>("VolumeChange24h_Lag_1")
                        .HasColumnType("float");

                    b.Property<double?>("VolumeChange24h_Lag_2")
                        .HasColumnType("float");

                    b.Property<bool?>("VolumeSpikeSignal")
                        .HasColumnType("bit");

                    b.Property<double?>("Volume_Rolling_Std_6h")
                        .HasColumnType("float");

                    b.Property<double?>("Volume_Spike_Ratio")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("FeatureEngineerings");
                });

            modelBuilder.Entity("CryptoApi.Models.InvestorGrade", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("HoldingReturns")
                        .HasColumnType("float");

                    b.Property<double?>("QuantGrade")
                        .HasColumnType("float");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TAGrade")
                        .HasColumnType("float");

                    b.Property<double?>("TMInvestorGrade")
                        .HasColumnType("float");

                    b.Property<double?>("TMTraderGrade")
                        .HasColumnType("float");

                    b.Property<double?>("TMTraderGrade24hPctChange")
                        .HasColumnType("float");

                    b.Property<string>("TokenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TokenTrend")
                        .HasColumnType("int");

                    b.Property<int?>("TradingSignal")
                        .HasColumnType("int");

                    b.Property<double?>("TradingSignalsReturns")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("InvestorGrades");
                });

            modelBuilder.Entity("CryptoApi.Models.Sentiment", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double?>("NegativeReddit")
                        .HasColumnType("float");

                    b.Property<double?>("NeutralReddit")
                        .HasColumnType("float");

                    b.Property<double?>("PositiveReddit")
                        .HasColumnType("float");

                    b.Property<int?>("PostCountReddit")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Sentiments");
                });
#pragma warning restore 612, 618
        }
    }
}
