// <auto-generated />
using System;
using CryptoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CryptoApi.Models.CoinData", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PercentChange1h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PercentChange24h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PercentChange30d")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PercentChange60d")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PercentChange7d")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PercentChange90d")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume24h")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VolumeChange24h")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("CoinDatas");
                });

            modelBuilder.Entity("CryptoApi.Models.InvestorGrade", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HoldingReturns")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QuantGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMInvestorGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TMTraderGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TMTraderGrade24hPctChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TokenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenTrend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradingSignal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TradingSignalsReturns")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("InvestorGrades");
                });

            modelBuilder.Entity("CryptoApi.Models.Sentiment", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("NegativeReddit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeutralReddit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositiveReddit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCountReddit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Sentiments");
                });
#pragma warning restore 612, 618
        }
    }
}
